# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "MuNCHER"
description:	       "Soil Sampling Robot"
author:              "Matt Farmar, Ian Walsh, Kenta Terasaki, Zayn Patel, and Mihir Vemuri"
#baseurl: "/the_muncher" # the subpath of your site, e.g. /blog
#url: "https://zaynpatel.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
