# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'MuNCHER'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Mechanical Design' , url: 'mechdes'}
- {name: 'Electrical Design',       url: 'elecdes'}
- {name : 'Software Design', url: 'softdes'}
- {name: 'About',              url: 'about'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link:    'https://github.com/olincollege/The-MuNCHER'}